'use strict';

module.exports = {
  DokuwikiPlugin: require('./dokuwiki-plugin'),
  DrupalPlugin: require('./drupal-plugin'),
  GoProject: require('./go-project'),
  HarborComponent: require('./harbor-component').HarborComponent,
  HarborGoComponent: require('./harbor-component').HarborGoComponent,
  JavaApplication: require('./java-application'),
  Java8Application: require('./java-application/java8'),
  Java16Application: require('./java-application/java16'),
  NginxModule: require('./nginx-module'),
  Node10Application: require('./node-application'),
  Node12Application: require('./node-application/node12'),
  Node14Application: require('./node-application/node14'),
  Node15Application: require('./node-application/node15'),
  Node16Application: require('./node-application/node16'),
  NodeApplication: require('./node-application'),
  PeclComponent: require('./pecl-component'),
  PHPApplication: require('./php-application'),
  PHP73Application: require('./php-application'),
  PHP74Application: require('./php-application/php74'),
  PHP80Application: require('./php-application/php80'),
  RubyApplication: require('./ruby-application'),
  Ruby26Application: require('./ruby-application'),
  Ruby27Application: require('./ruby-application/ruby27'),
  Ruby30Application: require('./ruby-application/ruby30'),
  WordPressPlugin: require('./wordpress-plugin'),
};
